In [3]:
import numpy as np
import time

1757440342.820443

In [25]:
def python_version():
    start_time=time.time()
    A=list(range(100000))
    B=list(range(100000))
    C=[A[i]+B[i] for i in range(len(A))]
    end_time=time.time()
    sure=end_time-start_time
    print(f'Python versiyonu çalışma süresi : {sure}')

In [23]:
def numpy_version():
    start_time=time.time()
    A=np.arange(100000)
    B=np.arange(100000)
    C=A+B
    end_time=time.time()
    sure=end_time-start_time
    print(f'Numpy versiyonu çalışma süresi : {sure}')


In [26]:
python_version()
numpy_version()

Python versiyonu çalışma süresi : 0.012021303176879883
Numpy versiyonu çalışma süresi : 0.001050710678100586


In [28]:
list1=[1,2,3,4,5,6,7]
arr1=np.array(list1)

In [30]:
arr1

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
arr1.astype(float)

array([1., 2., 3., 4., 5., 6., 7.])

In [32]:
a=np.arange(0,25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
a=np.arange(0,25,2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [34]:
a[3]

6

In [35]:
b=np.arange(0,123,4)
b

array([  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,
        52,  56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100,
       104, 108, 112, 116, 120])

In [38]:
c=np.arange(100,-20,-9)
c

array([100,  91,  82,  73,  64,  55,  46,  37,  28,  19,  10,   1,  -8,
       -17])

In [40]:
#sıfırlardan oluşan bir dizi
zeros=np.zeros(10).astype(int)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
ones=np.ones(10).astype(float)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
#repeat(sayı,kac tanee)
rp=np.repeat(22,4)
rp

array([22, 22, 22, 22])

In [43]:
d=np.array([1,3,6,8])
rp1=np.repeat(d,2)
rp1

array([1, 1, 3, 3, 6, 6, 8, 8])

In [45]:
sayilar=list(range(1,21))
tek_sayilar=[]
for i in sayilar:
    if i%2==1:
        tek_sayilar.append(i)
tek_sayilar        

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [51]:
np_sayilar=np.arange(1,20)
tek_numpy=np_sayilar[np_sayilar %2==1]
tek_numpy

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [52]:
#linspace(başlangıç,bitis,adet)

lns=np.linspace(20,30,3)
lns

array([20., 25., 30.])

In [53]:
np.random.randint(100,300,2)


array([127, 297])

In [59]:
np.random.seed(20)
np.random.randint(0,500,10)

array([355, 474, 271, 223, 412, 218, 393, 404, 331, 278])

In [60]:
np.random.seed(202)
np.random.randint(0,500,10)

array([403, 151,  60, 460, 296, 425, 185, 263, 358,  86])

In [61]:
a=np.random.randint(100,309,34)
a

array([229, 299, 148, 242, 247, 109, 130, 136, 225, 280, 187, 217, 120,
       204, 190, 237, 307, 143, 152, 219, 167, 231, 277, 152, 300, 218,
       110, 286, 224, 212, 237, 167, 238, 172])

In [62]:
a.max()

307

In [63]:
a.min()

109

In [64]:
a

array([229, 299, 148, 242, 247, 109, 130, 136, 225, 280, 187, 217, 120,
       204, 190, 237, 307, 143, 152, 219, 167, 231, 277, 152, 300, 218,
       110, 286, 224, 212, 237, 167, 238, 172])

In [65]:
a.sum()

7012

In [67]:
a.mean()

206.23529411764707

In [68]:
a.std()

56.23326356166648

In [69]:
A = np.array([[1,11,3],[4,15,6],[7,9,8]])
A


array([[ 1, 11,  3],
       [ 4, 15,  6],
       [ 7,  9,  8]])

In [70]:
A.sum()

64

In [71]:
np.amin(A,axis=0)

array([1, 9, 3])

In [72]:
np.amax(A,axis=1)

array([11, 15,  9])

In [74]:
b=np.random.randint(10,30,14)
b

array([28, 17, 22, 23, 23, 27, 29, 25, 17, 27, 23, 17, 22, 14])

In [75]:
b[2:4]

array([22, 23])

In [76]:
b[-5:-1]

array([27, 23, 17, 22])

In [77]:
# son 5 veri
b[-5:]

array([27, 23, 17, 22, 14])

In [78]:
b[:7]

array([28, 17, 22, 23, 23, 27, 29])

In [79]:
d=np.arange(21)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [80]:
# d dizisi içerisinde çift sayıların yerine 5 yazan kodu yazın
r=np.where(d%2==0,5,d)
r

array([ 5,  1,  5,  3,  5,  5,  5,  7,  5,  9,  5, 11,  5, 13,  5, 15,  5,
       17,  5, 19,  5])

In [81]:
a = np.array([10,25,36,np.nan, 69,85,np.nan])
a

array([10., 25., 36., nan, 69., 85., nan])

In [84]:
np.isnan(a)

array([False, False, False,  True, False, False,  True])

In [87]:
a[np.isnan(a)]=100

In [88]:
a

array([ 10.,  25.,  36., 100.,  69.,  85., 100.])

In [89]:
c1 = np.arange(10,61,10)
c2 = np.array([12,25,30,44,60,55,50])

In [90]:
c1

array([10, 20, 30, 40, 50, 60])

In [91]:
c2

array([12, 25, 30, 44, 60, 55, 50])

In [93]:
np.setdiff1d(c1,c2) #c1 de olup c2 de olmayan değerler

array([10, 20, 40])

In [94]:
np.setdiff1d(c2,c1)

array([12, 25, 44, 55])

In [95]:
c2

array([12, 25, 30, 44, 60, 55, 50])

In [97]:
c2[::-1]   #verileri ters çevir

array([50, 55, 60, 44, 30, 25, 12])

In [99]:
 np.flip(c2)     #verileri ters çevir

array([50, 55, 60, 44, 30, 25, 12])

In [100]:
a3 = np.array([[3,4,8,7],[11,24,10,85],[35,5,47,2]])
a3

array([[ 3,  4,  8,  7],
       [11, 24, 10, 85],
       [35,  5, 47,  2]])

In [101]:
a3[::-1]

array([[35,  5, 47,  2],
       [11, 24, 10, 85],
       [ 3,  4,  8,  7]])

In [104]:
#reshape()
p1=np.arange(0,121).reshape(11,11)
p1


array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])

In [105]:
a1=[5,6,7]
a2=[2,4,6]
a3=np.multiply(a1,a2)
a3


array([10, 24, 42])

In [107]:
a4 = np.array([5,6,7])
a5 = np.array([4,2,3])

a4*a5

array([20, 12, 21])

In [109]:
M=np.random.randint(0,1000,100).reshape(10,10)
M

array([[593,  90, 806, 389, 696, 182, 931, 419,  12, 354],
       [241, 449, 658, 824, 913, 593, 105,  14, 559, 335],
       [345,  33, 860, 481, 976,  98, 681, 217,  99, 953],
       [804, 191, 400, 195, 610, 780, 148, 805, 565, 205],
       [557, 806, 787, 199, 697, 953, 462, 729,  94, 134],
       [ 75, 427, 280, 580, 266, 235, 989, 367, 302, 486],
       [982, 866, 442, 623, 151, 868, 241, 440, 957, 980],
       [480, 641, 786, 539, 636, 851, 916, 621, 345, 257],
       [ 37, 130, 888, 423, 310, 882, 717, 106, 771, 516],
       [ 84, 163,  92, 766, 994,  95, 460, 905, 304, 626]])

In [110]:
filtered=M[M<500]
filtered

array([ 90, 389, 182, 419,  12, 354, 241, 449, 105,  14, 335, 345,  33,
       481,  98, 217,  99, 191, 400, 195, 148, 205, 199, 462,  94, 134,
        75, 427, 280, 266, 235, 367, 302, 486, 442, 151, 241, 440, 480,
       345, 257,  37, 130, 423, 310, 106,  84, 163,  92,  95, 460, 304])

In [112]:
#birim matris(identity)
a=np.eye(4).astype(int)
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [115]:
#diagonal matris
d=np.diag(np.arange(1,7))
d

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [116]:
d=np.diag([2,4,6,8])
d

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

In [119]:
M1=np.random.randn(3,4)
M1

array([[-0.62472361, -1.47201886, -0.58781023, -0.89775407],
       [-0.44905533, -0.63138179,  0.19885658,  0.31121558],
       [-0.54998607, -0.25524031,  1.4905993 ,  0.46936518]])

In [120]:
U = np.triu(M1)
U

array([[-0.62472361, -1.47201886, -0.58781023, -0.89775407],
       [ 0.        , -0.63138179,  0.19885658,  0.31121558],
       [ 0.        ,  0.        ,  1.4905993 ,  0.46936518]])

In [121]:

L = np.tril(M1)
L

array([[-0.62472361,  0.        ,  0.        ,  0.        ],
       [-0.44905533, -0.63138179,  0.        ,  0.        ],
       [-0.54998607, -0.25524031,  1.4905993 ,  0.        ]])

In [123]:
m2=np.random.randint(10,45,16).reshape(4,4)
m2

array([[37, 37, 18, 30],
       [19, 29, 31, 32],
       [13, 20, 23, 33],
       [17, 43, 37, 12]])

In [124]:
np.transpose(m2)

array([[37, 19, 13, 17],
       [37, 29, 20, 43],
       [18, 31, 23, 37],
       [30, 32, 33, 12]])

In [126]:

np.linalg.det(m2)

87648.00000000003

In [128]:
# Hisse senedi uyulaması 
# Getiri = ((Bugünkü fiyat - dünkü fiyat) / Dünkü fiyat)*100
prices = np.array([1000,1020,1100,1045,1150,1200,1100])
getiriler_farki=np.diff(prices)
result=getiriler_farki/prices[:-1]*100
print(f'Günlük getiri (%) {result}')
print(f'Ortalama günlük getirisi : {np.mean(result)} %')

Günlük getiri (%) [ 2.          7.84313725 -5.         10.04784689  4.34782609 -8.33333333]
Ortalama günlük getirisi : 1.8175794830795506 %


In [129]:
# Başlangıç nüfusu 10m olan ülkenin yıllık büyüme oranı %2 dir 10 yıllık nüfus tahminini yapınız.
# P(t) = P0* e^rt
baslangic_nufusu = 10000000
buyume_orani = 0.02
yillar = np.arange(1,11)
populasyon = baslangic_nufusu * np.exp(buyume_orani * yillar)
print(f'10 yıllık nüfus tahmini :')
populasyon

10 yıllık nüfus tahmini :


array([10202013.40026756, 10408107.74192388, 10618365.4654536 ,
       10832870.67674959, 11051709.18075648, 11274968.51579376,
       11502737.98857227, 11735108.7099181 , 11972173.6312181 ,
       12214027.5816017 ])